version: '3.0'
services:
  web:
    container_name: django-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db
  # MySQL
  db: 
    container_name: mysql-db
    image: mysql:8.0.34
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${SQL_DATABASE}
    ports:
      - 3306:3306
    # PostgreSQL
    # db:
    #   container_name: postgres-db
    #   image: postgres:14
    #   volumes:
    #     - postgres_data:/var/lib/postgresql/data/
    #   ports:
    #     - 5432:5432
    #   environment:
    #     - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  #postgres_data:
  mysql_data:
